### ISSUE TITLE
Ошибки добавления товара

### ISSUE THREAD

**Issue by vesnins** [igofftt/vspn_shop#3]
- [x] 1. Неудобно, что нужно перезагружать страницу товаров, чтобы увидеть изменения.
- [x] 2. Как увидеть товар, чтобы проверить отображение?
- [x] 3. Сломалось добавление категории
- [x] 4. Не сохраняются характеристики товара
- [x] 5. Фотография, выбранная главной, таковой на сайте не является.
- [x] 6. Ссылка из меню каталога (желтый фон) не ведет на категорию "Стеновые панели", а отдаёт ссылку http://185.22.60.180:8030/catalog/7?cat=14

**Comment by igofftt** [comment]
2. добавил кнопку которая откроет в новом окне продукт

**Comment by igofftt** [comment]
3. добавить поле `ALTER TABLE "menu" ADD COLUMN "system_name" character varying(64)`
